### PR TITLE
new model: DeepSEA/beluga

### PR DESCRIPTION
**Pull request by Avsecz**
- [x] wrote custom model for loading the torch file
- [X] add `predictor_names.txt` file
- [X] fill in the details marked with TODO
- [ ] save test predictions:

Either:
```bash
kipoi test . -o expect.h5
```
or
```bash
kipoi predict . \
  --source=dir \
  --dataloader_args='{"intervals_file": "sample.bed3", "fasta_file": "hg19.fa"}' \
  --keep_inputs \
  -o expect.h5
```
- [ ] make sure predictions stored in the hdf5 file under `preds` are indeed what we expected
- [ ] test predictions
```bash
kipoi test . -e expect.h5
```
- [ ] upload `expect.h5` to zenodo or S3

### CODE REVIEW

**Comment by Avsecz** [comment]
@jzthree Could you 
- fill in the details in model.yaml file
- provide a txt file where one row is the output task name (e.g. which TF/cell-type etc). Example for DeepSEA: https://github.com/kipoi/models/blob/master/DeepSEA/predictor_names.txt

I added you to the repo so you can directly put to the branch.

Do you have any example predictions for some genomic intervals we could use to validate model predictions?

**Comment by jzthree** [comment]
Thanks @Avsecz ! I filled in the TODO informations and the `predictor_names.txt`. 

For example prediction, I do have one at https://github.com/FunctionLab/ExPecto/blob/master/example/example.vcf.shift_0.diff.h5

The input is generated from the following vcf file by taking [position-999, position+1000] interval.
https://github.com/FunctionLab/ExPecto/blob/master/example/example.vcf

The first 10 entries in the h5 file are predictions for the forward direction and the last 10 are for reverse complement.

**Comment by Avsecz** [comment]
Great! Thanks! I will reformat the hdf5 file to be in the format we expect and then we are good to go

**Comment by DerThorsten** [comment]
with #142  the models tests pass, only the tests in the common environment fail

**Comment by Avsecz** [comment]
Oh I think I know what's going on. Shared env uses a new pytorch version and this requires the old one. Let me exclude that model from https://github.com/kipoi/models/blob/master/shared/envs/models.yaml

**Comment by DerThorsten** [comment]
still needs https://github.com/kipoi/models/pull/142 to be merged in

**Comment by DerThorsten** [comment]
looks like we can merge this

**Comment by Avsecz** [comment]
@jzthree I (finally) managed to test the model with your reference file (it works). I saw you recently converted the model to PyTorch 1+ (https://github.com/FunctionLab/ExPecto/commit/5cdaa16b0e9c00a266370a68577c6737ed7036db). Could you please upload the new pytorch 1+ file to Zenodo (https://zenodo.org/record/1744799) so that I can update it?

**Comment by jzthree** [comment]
@Avsecz  Yes I updated the new pytorch 1+ file https://zenodo.org/record/3402406#.XXUsM5NKjzJ.  Sorry for the delay - I was traveling with limited internet access.

**Comment by Avsecz** [comment]
Awesome. Thanks!

**Comment by Avsecz** [comment]
I updated the model to PyTorch. Predictions are exactly the same as before. Thanks again.

**Pull request merged**
