### PR TITLE
add Attentive Chrome models from "Attend and Predict: Understanding Gene Regulation by Selective Attention on Chromatin"

### PR DESCRIPTION
**Pull request by jacklanchantin**

### CODE REVIEW

**Comment by Avsecz** [comment]
Looks good! Can you split the authors into separate list elements, e.g.

```yaml
authors:
  - name: first author
    github: ...
  - name: second author
```

**Comment by jacklanchantin** [comment]
Yes, absolutely. I'm also not sure if we formatted everything right, but
the tests worked.

**Comment by Avsecz** [comment]
Let's see if it will the environment will be setup properly on the next commit. (Seems that circleCi was experiencing some issues recently)

**Comment by jacklanchantin** [comment]
Looks like there is an error in the model-template.yaml file. I'm not sure how to format that file since there wasn't an explicit template (we used the deepbind model files for a template). Should we not put authors and contributors there?

**Comment by Avsecz** [comment]
There is a small formatting mistake for the authors. The `github` entry for the author does shouldn't have `-` in the same row.

```yaml
authors:
  - name: First Author
    github: first_author
  - name: Second author
    email: email...
  - name: Third author
...
```

**Comment by Avsecz** [comment]
Tests pass. We just need to restrict tests to only run for a single model

**Comment by jacklanchantin** [comment]
Yes - I noticed that it was running for each model.

Is this related to the error we got for each of the models:

ValueError: Conda environment test-kipoi-AttentiveChrome__E037 doesn’t exist

**Comment by Avsecz** [comment]
Can you add the following file to the `AttentiveChrome` directory: `test_subset.txt` with the following content

```
E003
```

This will test only the `E003` model.

**Comment by Avsecz** [comment]
I also added you to the `kipoi/models` repo so you can make new branches directly on the repo (in case you have to fix something).

**Comment by Avsecz** [comment]
Seems that it's working. One more thing: is it possible to provide a smaller `test.csv` file? It currently contains 6600 genes which take some time to predict (e.g. 15 minutes). I think 10-50 genes would be more than enough for testing purposes.

**Comment by jacklanchantin** [comment]
Yes - that's a good idea. I'll do that now. Thanks!

**Comment by jacklanchantin** [comment]
Ok I think it's working now! Anything else I should do?

**Comment by Avsecz** [comment]
Looks good! Thanks!

**Comment by Avsecz** [comment]
AttentiveChrome should be displayed on kipoi.org in the next hour.

**Comment by Avsecz** [comment]
Model is online: http://kipoi.org/models/AttentiveChrome/ :)

**Pull request merged**
