### PR TITLE
mtsplice added

### PR DESCRIPTION
**Pull request by MuhammedHasan**

### CODE REVIEW

**Comment by MuhammedHasan** [comment]
I cannot merge this branch. @Avsecz can you please merge it?

**Comment by Hoeze** [comment]
@MuhammedHasan You cannot merge because tests are failing.
I could merge it, but would you mind fixing this error first?
```
INFO [kipoi.cli.env] Done writing the environment file!
Traceback (most recent call last):
  File "/opt/conda/bin/kipoi", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/kipoi/__main__.py", line 105, in main
    command_fn(args.command, sys.argv[2:])
  File "/opt/conda/lib/python3.7/site-packages/kipoi/cli/env.py", line 696, in cli_main
    command_fn(args.command, raw_args[1:])
  File "/opt/conda/lib/python3.7/site-packages/kipoi/cli/env.py", line 457, in cli_create
    envdb.save()
  File "/opt/conda/lib/python3.7/site-packages/kipoi/env_db.py", line 128, in save
    self.db.purge()
  File "/opt/conda/lib/python3.7/site-packages/tinydb/database.py", line 250, in __getattr__
    return getattr(self.table(self.default_table_name), name)
AttributeError: 'Table' object has no attribute 'purge'
ERROR [kipoi.cli.source_test] Model MMSplice/mtsplice failed: could not invoke ['kipoi', 'env', 'create', '--source', 'kipoi', '--env', 'test-kipoi-MMSplice__mtsplice', 'MMSplice/mtsplice', '--verbose'] 
```

**Comment by MuhammedHasan** [comment]
Error is not related with MTSplice. https://github.com/kipoi/kipoi/issues/502
Let's merge it first :D, then we can fix the error.

**Comment by Hoeze** [comment]
OK done, please check @MuhammedHasan  :)

**Pull request merged**
