### PR TITLE
Update model-template.yaml

### PR DESCRIPTION
**Pull request by jacklanchantin**

### CODE REVIEW

**Comment by jacklanchantin** [comment]
@Avsecz sorry for the confusion, but how do I update the "contributed by" entry in the http://kipoi.org/models/AttentiveChrome/ page? If anyone has questions about the models, they should contact me - so it will be best if it shows my github account.

**Comment by jacklanchantin** [comment]
Or maybe it just takes a few minutes to push to the hosted server.

**Comment by Avsecz** [comment]
The webpage currently uploads once per day (https://github.com/kipoi/website/blob/master/.circleci/config.yml#L105-L111). I just manually issued a re-build. It should be online in 10 minutes.

**Comment by Avsecz** [comment]
It got updated.

**Comment by jacklanchantin** [comment]
Thanks a lot Žiga - I appreciate the help!

**Comment by Avsecz** [comment]
You're welcome. Happy to help.

**Pull request merged**
