### PR TITLE
Framepool variant effect prediction dataloader

### PR DESCRIPTION
**Pull request by Hoeze**
Was quite some guessing to get this working.
Is this the intended way to re-use other dataloaders?

### CODE REVIEW

**Review by haimasree — APPROVED** [review]
Thanks! I think this is indeed the intended way to add dataloaders. I will verify this with Ziga and will provide documentation.

**Comment by Hoeze** [comment]
Thanks @haimasree!
Another thing I had to find out by guessing:
To use this dataloader, you need to specify `--dataloader Framepool/VariantEffect`.

AFAIK there is no way to:
- specify the dataloader as python module (e.g. `kipoi.models.Framepool.Varianteffect` or `kipoiseq.dataloaders.SingleVariantUTRDataLoader`)
- list working dataloaders (e.g. `kipoi ls --dataloader Framepool` / `kipoi ls -a Framepool`)

**Comment by haimasree** [comment]
You are correct. There is no way to do either of them in Kipoi. I will bring this up with Ziga and can devise a further plan.

**Comment by Avsecz** [comment]
Good point. Let's continue the discussion about the requested feature in the issue you raised: https://github.com/kipoi/kipoi/issues/582

**Pull request merged**
