### PR TITLE
CNN models for epidermal differentiation - Basset style, tensorflow

### PR DESCRIPTION
**Pull request by vervacity**
Hello, submitting models to Kipoi! Thank you!

### CODE REVIEW

**Comment by haimasree** [comment]
@vervacity  Thanks a lot :)

I have a question about the dependencies requirement you mentioned in model.yaml. Do you need python=2.7 or anything like 3.5/3.6 will do? Also, what is the exact version of h5py and tensorflow you have in your environment?
If you are using conda for virtual environment management the following line will give you the exact version
```
conda env export --no-build > env.yml | grep python
conda env export --no-build > env.yml | grep h5py
conda env export --no-build > env.yml | grep tensorflow

```

Unfortunately the tests are failing. Can you please let me know if you can access [this link](https://app.circleci.com/pipelines/github/kipoi/models/668/workflows/091644a4-fc9b-4dec-bdcc-d6c592ec50e6/jobs/2101)?

**Comment by vervacity** [comment]
@haimasree thank you!

In terms of the dependencies, I just realized this is no longer in my tensorflow codebase so yes I think python 3.5/3.6 should work (since i'm submitting the TF meta/data/index files), I will test this! tensorflow is 1.10, and for h5py I think I don't have a preference since i'm not submitting any h5py files, so please let me know what h5py version might be best for kipoi compatibility.

Yes now have set up CircleCI to take a look - I had this same issue locally, where there's some issue with getting the `model.yaml` into an `OrderedDict` - I have multiple models in my `model.tsv`, so there must be some issue in matching up the models into the args? Please let me know if you have any thoughts. 

As a workaround, I have done tests in individual folders and the models pass `kipoi test`.

**Comment by haimasree** [comment]
@vervacity Soryr for late reply, it was holiday yesterday. 
Although there are other versions, the most commonly used h5py version in kipoi is 2.10.0
For example, rbp_eclip has about 102 models and  here is the [model-template.yaml](https://github.com/kipoi/models/blob/master/rbp_eclip/model-template.yaml). Perhaps changing model.yaml to model-template.yaml will be enough?

**Comment by vervacity** [comment]
@haimasree no problem. sounds good for the h5py version, i'll update that. Renaming to `model-template.yaml` didn't work, it just tells me the model doesn't exist.

**Comment by haimasree** [comment]
Okay I will take  a look.

**Comment by haimasree** [comment]
Can you please try the following 
1. ```mv epidermal_basset/model.yaml epidermal_basset/model-template.yaml```
2. Replace dependencies section of epidermal_basset/model-template.yaml  by the following
```
dependencies:
    conda: # install via conda
      - python=3.6
      - h5py=2.10.0
      - pip=20.2.4
    pip:   # install via pip
      - kipoiseq
      - tensorflow==1.8
```
3. Dependencies of all remaining model.yaml in models/* should look like the following
```
dependencies:
    conda: # install via conda
      - python
      - h5py
    pip:   # install via pip
      #- keras>=2.0.4
      - tensorflow==1.8
```

Ideally these two sets of dependencies should match but thats a whole lot of copying. I found it easiest to remove =2.7 with '' and >=1.8 to ==1.8. The key thing here is if there are pinned versions in the template level dependency, the model level dependencies must either match it exactly or may remain unpinned. 

I will also suggest to add a file called test_subset.txt at the top level and add only a few of the models like so -
```
encode-roadmap.basset.clf.testfold-0
ggr.basset.clf.pretrained.folds.testfold-0
```
Otherwise kipoi ci will test all of them. If you think that is necessary no need to add this file. 

Please commit the above changes. Let me know if you have any question.

**Comment by haimasree** [comment]
Since I did not hear back from you I am proceeding with the above changes after accepting the pr. Let me know if you disagree.

**Comment by vervacity** [comment]
So sorry for the delay in reply, that's perfect, thank you so much!! please let me know if i can be of any more help!

**Pull request merged**
