### PR TITLE
Faster Dataloader

### PR DESCRIPTION
**Pull request by jorenretel**
Made the dataloader faster by changing how the FastaExtractor works. By keeping the file object open (FastaFile from pysam) instead of repetitively opening and closing it, the speed of the dataloader is significantly improved. This code change would potentially be more in place in genomelake, since this dataloader is just an example of where this FastaExtractor it is used. However, the github repository kundajelab/genomelake gives a 404. If instead of accepting this pull request you can point me to the correct repo to submit a pull-request that would be probably the better solution.

### CODE REVIEW

**Comment by krrome** [comment]
Great suggestion, thank you @jorenretel. I will propagate the suggested update of FastaExtractor as a PR to genomelake repository and mention you.

**Comment by jorenretel** [comment]
Great. Thank you very much!

**Comment by jisraeli** [comment]
Looks great. I made https://github.com/kundajelab/genomelake public, looking forward to PR!

**Comment by Avsecz** [comment]
great! I will close this PR. Thanks @jorenretel

**Pull request closed without merging**
