### PR TITLE
added 322 ENCODE trained lsgkm-SVM models

### PR DESCRIPTION
**Pull request by krrome**

### CODE REVIEW

**Comment by krrome** [comment]
There must be a dependency / requirement issue.. I'll fix it asap

**Comment by Avsecz** [comment]
can you please also include the `test_subset.txt` file in the root of `lsgkm-SVM` folder like https://github.com/kipoi/models/blob/FactorNet/FactorNet/test_subset.txt

**Comment by Avsecz** [comment]
add to change `FastaFile` to `Fastafile`

**Comment by Avsecz** [comment]
now I have the model loading error:

```python
$ kipoi test lsgkm-SVM/Tfbs/Nanogsc33759/H1hesc/Haib_V0416102/ 
INFO [kipoi.data] successfully loaded the dataloader from lsgkm-SVM/Tfbs/Nanogsc33759/H1hesc/Haib_V0416102/dataloader.py::SeqDataset
Traceback (most recent call last):
  File "/opt/modules/i12g/anaconda/3-5.0.1/envs/kipoi-gksvm/bin/kipoi", line 11, in <module>
    sys.exit(main())
  File "/opt/modules/i12g/anaconda/3-5.0.1/envs/kipoi-gksvm/lib/python2.7/site-packages/kipoi/__main__.py", line 74, in main
    command_fn(args.command, sys.argv[2:])
  File "/opt/modules/i12g/anaconda/3-5.0.1/envs/kipoi-gksvm/lib/python2.7/site-packages/kipoi/cli/main.py", line 53, in cli_test
    mh = kipoi.get_model(args.model, args.source)
  File "/opt/modules/i12g/anaconda/3-5.0.1/envs/kipoi-gksvm/lib/python2.7/site-packages/kipoi/model.py", line 98, in get_model
    Mod = load_model_custom(**md.args)
  File "/opt/modules/i12g/anaconda/3-5.0.1/envs/kipoi-gksvm/lib/python2.7/site-packages/kipoi/model.py", line 150, in load_model_custom
    return getattr(load_module(file), object)
  File "/opt/modules/i12g/anaconda/3-5.0.1/envs/kipoi-gksvm/lib/python2.7/site-packages/kipoi/utils.py", line 37, in load_module
    module = imp.load_source(module_name, path)
  File "model.py", line 14
    print('>{}'.format(i), file=wf)
```

**Comment by Avsecz** [comment]
ok. pushed the change. It was the print and python2 issue

**Pull request merged**
