### PR TITLE
Update in mmsplice, version fixes, refactoring, modules support dropp…

### PR DESCRIPTION
**Pull request by MuhammedHasan**
…ed because of reduncy between modularpredictions

### CODE REVIEW

**Comment by Avsecz** [comment]
Can you merge the master branch into this branch?

**Comment by MuhammedHasan** [comment]
@Avsecz I am not authorized to merge it to master. Also, I am not sure why tests are failing.

**Comment by Avsecz** [comment]
I meant to do the following merge: master -> this branch (not this branch -> master).

**Comment by MuhammedHasan** [comment]
> I meant to update this branch with the most recent master branch (i.e. do the following merge: master -> this branch, not this branch -> master.

I think it is already the head of master branch. There is nothing to merge with the master branch.

**Comment by Avsecz** [comment]
You probably forgot to pull the most recent master branch locally before merging it.

**Comment by Avsecz** [comment]
Ok. something weird is going on. You may be right:)

**Comment by Avsecz** [comment]
Ok. Moving to a new cache-id fixed the issue. Seems that there was something wrong with retrieving the old cache.

**Comment by Avsecz** [comment]
Seems that the install fails. Can you specify `pysam` in the conda dependency?

**Comment by MuhammedHasan** [comment]
@Avsecz can you merge?

**Pull request merged**
