### PR TITLE
DeepLiver models

### PR DESCRIPTION
**Pull request by cbravo93**
Hi!

I would like to add the DeepLiver models to the zoo. You can find the preprint describing the models at https://www.biorxiv.org/content/10.1101/2022.12.08.519575v1 

Since I built the model using the internal keras from tensorflow (keras=2.2.4-tf, tensorflow=1.15), I had to add my own model class. It is exactly the same as kipoi's KerasModel, but using tensorflow.keras instead of keras for the imports.

Local tests have been successful, let me know if more information is needed!

C

### CODE REVIEW

**Comment by ivyraine** [comment]
Hey C,

Just looking at this now, sorry about the delay! Looks good- let's see if the tests pass again

**Comment by ivyraine** [comment]
Ah hold on for a second- this test failure is related to other changes in the repo! Let me take a look at them

**Comment by cbravo93** [comment]
Thanks for taking a look! Let me know if I need to update anything :)

**Comment by ivyraine** [comment]
Alright the tests are fixed now, should be good to go!

**Pull request merged**
