### PR TITLE
Adjust APARENT model

### PR DESCRIPTION
**Pull request by Hoeze**
- Fix mistake in proximal and distal score index
- Implement adjustable isoform window in model

### CODE REVIEW

**Comment by Hoeze** [comment]
@haimasree How can the tests pass here when the expected predictions are nonsense?

**Comment by haimasree** [comment]
> @haimasree How can the tests pass here when the expected predictions are nonsense?

Sorry dont know what you mean. In general ```kipoi test <model> --source=kipoi``` checks for three things -

1. Whether the model specific conda environment can be created and activated successfully (which runs fine here since the dependencies did not change)
2. Whether the data scheme that the dataloader outputs and the model expects match or not
3. Optionally, if there is a ```test``` field in model.yaml the predictions in the h5 file is compared with the prediction produced by the the model. In this case only site_probabilities has a test prediction to test against. Are you talking about that?

**Review by haimasree — APPROVED** [review]
Overall I think it looks good. Let me know if I can merge.

**Comment by Hoeze** [comment]
Thanks for the explanation @haimasree :+1: 
> Do you suspect a bug here?

No, I was confused because the predictions definitely changed since last time.
I just did not see that there is no `test` field in the `veff` part :facepalm: 

> Overall I think it looks good. Let me know if I can merge.
Feel free to merge then :+1:

**Pull request merged**
