### PR TITLE
Add APARENT model

### PR DESCRIPTION
**Pull request by Hoeze**
Add the APA Regression Net (APARENT) model for DNA sequence scoring and variant effect prediction.

This branch depends on the following pull request in kipoiseq:
https://github.com/kipoi/kipoiseq/pull/100

### CODE REVIEW

**Comment by haimasree** [comment]
@Hoeze Thanks :)
The tests are failing and the error is the following 
```
INFO [kipoi.cli.env] Inferred dataloader name: APARENT/site_probabilities from the model.
INFO [kipoi.cli.env] Environment name: test-kipoi-APARENT__site_probabilities
INFO [kipoi.cli.env] Output env file: /tmp/kipoi/envfiles/9ea3caac/test-kipoi-APARENT__site_probabilities.yaml
INFO [kipoi.cli.env] Done writing the environment file!
INFO [kipoi.cli.env] Creating conda env from file: /tmp/kipoi/envfiles/9ea3caac/test-kipoi-APARENT__site_probabilities.yaml

ResolvePackageNotFound: 
  - kipoi
  - pyranges
  - kipoiseq

Traceback (most recent call last):
Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed
  File "/home/circleci/miniconda3/bin/kipoi", line 8, in <module>
    sys.exit(main())
  File "/home/circleci/miniconda3/lib/python3.9/site-packages/kipoi/__main__.py", line 105, in main
    command_fn(args.command, sys.argv[2:])
  File "/home/circleci/miniconda3/lib/python3.9/site-packages/kipoi/cli/env.py", line 696, in cli_main
    command_fn(args.command, raw_args[1:])
  File "/home/circleci/miniconda3/lib/python3.9/site-packages/kipoi/cli/env.py", line 461, in cli_create
    kipoi_conda.create_env_from_file(env_file, use_stdout=args.verbose)
  File "/home/circleci/miniconda3/lib/python3.9/site-packages/kipoi_conda/utils.py", line 127, in create_env_from_file
    return _call_conda(cmd_list, use_stdout=use_stdout, dry_run=dry_run)
  File "/home/circleci/miniconda3/lib/python3.9/site-packages/kipoi_conda/utils.py", line 196, in _call_conda
    return _call_command("conda", extra_args, use_stdout, return_logs_with_stdout, dry_run=dry_run)
  File "/home/circleci/miniconda3/lib/python3.9/site-packages/kipoi_utils/utils.py", line 78, in _call_command
    raise Exception("could not invoke {0} \nreturn code:{1}\nadditional info:{2}".format(cmd_list, return_code, "".join(error_out)))
Exception: could not invoke ['conda', 'env', 'create', '--file', '/tmp/kipoi/envfiles/9ea3caac/test-kipoi-APARENT__site_probabilities.yaml'] 
return code:1

```
Can you try pinning versions of python and pip in under dependencies/conda in both dataloader.yaml and model.yaml.

**Comment by haimasree** [comment]
Also: Which version of tensorflow are you using?

**Comment by haimasree** [comment]
There is an easy way to install a package from a branch. Instead of writing kipoiseq you can just write 
```
git+https://github.com/Hoeze/kipoiseq.git
```
In this way we can test it right now in the model repo and I will fix it when you kipoiseq pr has been merged to master.

**Comment by Hoeze** [comment]
> @Hoeze Thanks :)
> The tests are failing and the error is the following
> 
> ```
> INFO [kipoi.cli.env] Inferred dataloader name: APARENT/site_probabilities from the model.
> INFO [kipoi.cli.env] Environment name: test-kipoi-APARENT__site_probabilities
> INFO [kipoi.cli.env] Output env file: /tmp/kipoi/envfiles/9ea3caac/test-kipoi-APARENT__site_probabilities.yaml
> INFO [kipoi.cli.env] Done writing the environment file!
> INFO [kipoi.cli.env] Creating conda env from file: /tmp/kipoi/envfiles/9ea3caac/test-kipoi-APARENT__site_probabilities.yaml
> 
> ResolvePackageNotFound: 
>   - kipoi
>   - pyranges
>   - kipoiseq
> ```

@haimasree This is likely due to missing conda channels.
Can I somehow configure the following config for conda?
```
channels:
  - conda-forge
  - bioconda
  - defaults
channel_priority: flexible
```

> Can you please try pinning versions of python and pip in under dependencies/conda in both dataloader.yaml and model.yaml?

I don't need pip for anything.
Also, any "keras>2.0.4" and "tensorflow>=1" will work since the only dependency is the `model.h5`.

I believe listing "keras>2.0.4<3" as dependency should be enough, right?

**Comment by Hoeze** [comment]
> There is an easy way to install a package from a branch. Instead of writing kipoiseq you can just write
> 
> ```
> git+https://github.com/Hoeze/kipoiseq.git
> ```
> 
> In this way we can test it right now in the model repo and I will fix it after your kipoiseq pr's merge to master.

Awesome, thanks for the hint :grin: 
Will do :)

**Comment by haimasree** [comment]
> > There is an easy way to install a package from a branch. Instead of writing kipoiseq you can just write
> > ```
> > git+https://github.com/Hoeze/kipoiseq.git
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In this way we can test it right now in the model repo and I will fix it after your kipoiseq pr's merge to master.
> 
> Awesome, thanks for the hint 😁
> Will do :)
This will only work with pip though. I believe conda does not have this functionality. So something like this should work
```
conda:
 - pip=21.0.1
pip:
 - git+https://github.com/Hoeze/kipoiseq.git
```

**Comment by haimasree** [comment]
> > @Hoeze Thanks :)
> > The tests are failing and the error is the following
> > ```
> > INFO [kipoi.cli.env] Inferred dataloader name: APARENT/site_probabilities from the model.
> > INFO [kipoi.cli.env] Environment name: test-kipoi-APARENT__site_probabilities
> > INFO [kipoi.cli.env] Output env file: /tmp/kipoi/envfiles/9ea3caac/test-kipoi-APARENT__site_probabilities.yaml
> > INFO [kipoi.cli.env] Done writing the environment file!
> > INFO [kipoi.cli.env] Creating conda env from file: /tmp/kipoi/envfiles/9ea3caac/test-kipoi-APARENT__site_probabilities.yaml
> > 
> > ResolvePackageNotFound: 
> >   - kipoi
> >   - pyranges
> >   - kipoiseq
> > ```
> 
> @haimasree This is likely due to missing conda channels.
> Can I somehow configure the following config for conda?
> 
> ```
> channels:
>   - conda-forge
>   - bioconda
>   - defaults
> channel_priority: flexible
> ```
> 
> > Can you please try pinning versions of python and pip in under dependencies/conda in both dataloader.yaml and model.yaml?
> 
> I don't need pip for anything.
> Also, any "keras>2.0.4" and "tensorflow>=1" will work since the only dependency is the `model.h5`.
> 
> I believe listing "keras>2.0.4<3" as dependency should be enough, right?

Two example which uses conda channels directly in the yaml files
- https://github.com/kipoi/models/blob/master/BPNet-OSKN/model.yaml#L24
- https://github.com/kipoi/models/blob/master/Framepool/dataloader.yaml#L50

Regarding versioning yes that should work. However, I will recommend to use tensorflow 1 right now since it is not well tested. I will soon start working on that.

**Comment by Hoeze** [comment]
Should be fine now @haimasree :)

**Comment by haimasree** [comment]
Excellent! :)

**Pull request merged**
